# from typing import TypedDict, List, Optional
# from pydantic import BaseModel

# class GraphState(TypedDict):
#     file_path: str
#     persona: str
#     raw_text: str
#     layout_type: str  # 'digital' or 'scanned'
#     summary: str
#     vector_status: str
#     error: Optional[str]




# from typing import TypedDict, List, Optional, Annotated, NotRequired
# import operator

# class GraphState(TypedDict):
#     # --- Your Original PDF Metadata ---
#     file_path: str
#     persona: str
#     raw_text: str
#     doc_category: str  # New field
#     doc_confidence: float
#     dna_samples: str
#     layout_type: str  # 'digital' or 'scanned'
#     vector_status: str
    
#     # --- Reflector & Feedback Loop Fields ---
#     query: str                       # The user's question about the PDF
#     draft: str                       # The current generated answer
#     critique: str                    # Feedback from the Reflector node
#     reflection_count: int            # Counter to prevent infinite loops
#     doc_category: str                # RESUME | RESEARCH_PAPER | DATASHEET | LEGAL | OTHER
#     document_dna: str                # Multi-point sampled text used for classification
#     is_accurate: bool                # Set by audit validator
    
#     # --- Accuracy & Error Handling ---
#     # Using Annotated with operator.add allows nodes to append to this list
#     # instead of overwriting it, perfect for "Automatic Feedback Logs"
#     errors: Annotated[List[str], operator.add] 
    
#     # --- Final Output ---
#     summary: str                     # The polished, verified final response

#     # --- Combined Workspace Summary Mode ---
#     is_combined: NotRequired[bool]
#     document_ids: NotRequired[List[int]]









from typing import TypedDict, List, Annotated, NotRequired
import operator

class GraphState(TypedDict):
    """
    GraphState for 94%+ Accuracy Agentic Loop.
    Optimized for 8GB RAM using Sequential Node Processing.
    """
    
    # --- 📄 Document Identity (The 'Eyes') ---
    file_path: str
    doc_category: str       # RESUME | TECHNICAL_LAB | COMPETITION_BRIEF | RESEARCH_PAPER | API_GUIDE | CERTIFICATE
    doc_confidence: float   # Probability score from DNA Classifier
    dna_samples: str        # The 4-point sampled text (0%, 33%, 66%, 100%)
    raw_text: str           # Full extracted text from parser
    layout_type: str        # 'digital' or 'scanned'
    
    # --- 🎭 User Selection ---
    persona: str            # The chosen role (e.g., 'ceo', 'security_auditor', 'cto') 
    query: str
    
    # --- 🧠 Agentic Loop & Self-Healing (The 'Brain') ---
    draft: str              # The current summary generated by the node_summarize
    is_accurate: bool       # Set by node_audit; triggers the loop back to summarize 
    critique: str           # Detailed feedback from the Auditor to guide the rewrite
    reflection_count: int   # Counter used by manager route to cap retries
    
    # --- 📝 Accuracy & Logging ---
    # Annotated with operator.add allows nodes to append errors without overwriting
    errors: Annotated[List[str], operator.add] 
    
    # --- 🏆 Final Verified Output ---
    summary: str            # The polished, verified final response shown to the user
    vector_status: str      # Status of indexing in sqlite-vec
    
    # --- 📂 Multi-Doc / Workspace Mode ---
    is_combined: NotRequired[bool]
    document_ids: NotRequired[List[int]]